name: Deploy to Prefect Cloud
on: [push]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.5"
          
      - name: Install dependencies
        run: pip install prefect

      - name: Login to Prefect Cloud
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_WORKSPACE: "mestrado-graziela/default"
        run: |
          prefect cloud login --key $env:PREFECT_API_KEY --workspace $env:PREFECT_WORKSPACE
          
      - name: Deploy Flow
        run: python deployments/deploy_hello.py
        env:
          PREFECT_DEFAULT_WORK_POOL_NAME: "default-agent-pool"
          PYTHONPATH: ${{ github.workspace }}