name: Deploy Hello World
on: [push]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      # 1. Baixa o código
      - uses: actions/checkout@v4

      # 2. Configura Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.5"

      # 3. Instala o Prefect
      - name: Install Prefect
        run: pip install prefect

      # 4. Autentica no Prefect Cloud
      - name: Login to Prefect Cloud
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
        run: prefect cloud login --key $env:PREFECT_API_KEY

      # 5. Registra o deployment
      - name: Deploy Flow
        run: python deployments/deploy_hello.py